-- SQL Seed Script for Categories
-- This script inserts 150 course categories into the 'categories' table.

INSERT INTO "categories" ("name", "slug", "status", "metadata") VALUES
('Web Development', 'web-development', 'active', '{}'),
('Mobile Apps', 'mobile-apps', 'active', '{}'),
('Programming Languages', 'programming-languages', 'active', '{}'),
('Game Development', 'game-development', 'active', '{}'),
('Database Design & Development', 'database-design-development', 'active', '{}'),
('Software Testing', 'software-testing', 'active', '{}'),
('Software Engineering', 'software-engineering', 'active', '{}'),
('E-Commerce Development', 'e-commerce-development', 'active', '{}'),
('Front-end Development', 'front-end-development', 'active', '{}'),
('Back-end Development', 'back-end-development', 'active', '{}'),
('Full-stack Development', 'full-stack-development', 'active', '{}'),
('DevOps & CI/CD', 'devops-cicd', 'active', '{}'),
('Blockchain & Cryptocurrency', 'blockchain-cryptocurrency', 'active', '{}'),
('Machine Learning', 'machine-learning', 'active', '{}'),
('Artificial Intelligence', 'artificial-intelligence', 'active', '{}'),
('Deep Learning', 'deep-learning', 'active', '{}'),
('Data Analysis', 'data-analysis', 'active', '{}'),
('Data Visualization', 'data-visualization', 'active', '{}'),
('Statistics', 'statistics', 'active', '{}'),
('Big Data', 'big-data', 'active', '{}'),
('Natural Language Processing', 'natural-language-processing', 'active', '{}'),
('Entrepreneurship', 'entrepreneurship', 'active', '{}'),
('Business Strategy', 'business-strategy', 'active', '{}'),
('Management', 'management', 'active', '{}'),
('Project Management', 'project-management', 'active', '{}'),
('Sales', 'sales', 'active', '{}'),
('Business Communication', 'business-communication', 'active', '{}'),
('Human Resources', 'human-resources', 'active', '{}'),
('Operations Management', 'operations-management', 'active', '{}'),
('Finance & Accounting', 'finance-accounting', 'active', '{}'),
('Real Estate', 'real-estate', 'active', '{}'),
('Supply Chain', 'supply-chain', 'active', '{}'),
('IT Certifications', 'it-certifications', 'active', '{}'),
('Network & Security', 'network-security', 'active', '{}'),
('Cyber Security', 'cyber-security', 'active', '{}'),
('Cloud Computing', 'cloud-computing', 'active', '{}'),
('Operating Systems', 'operating-systems', 'active', '{}'),
('Hardware', 'hardware', 'active', '{}'),
('Ethical Hacking', 'ethical-hacking', 'active', '{}'),
('Web Design', 'web-design', 'active', '{}'),
('Graphic Design', 'graphic-design', 'active', '{}'),
('UI/UX Design', 'ui-ux-design', 'active', '{}'),
('Design Tools', 'design-tools', 'active', '{}'),
('3D & Animation', '3d-animation', 'active', '{}'),
('Fashion Design', 'fashion-design', 'active', '{}'),
('Interior Design', 'interior-design', 'active', '{}'),
('Motion Graphics', 'motion-graphics', 'active', '{}'),
('Digital Marketing', 'digital-marketing', 'active', '{}'),
('Search Engine Optimization (SEO)', 'seo', 'active', '{}'),
('Social Media Marketing', 'social-media-marketing', 'active', '{}'),
('Content Marketing', 'content-marketing', 'active', '{}'),
('Email Marketing', 'email-marketing', 'active', '{}'),
('Public Relations', 'public-relations', 'active', '{}'),
('Branding', 'branding', 'active', '{}'),
('Advertising', 'advertising', 'active', '{}'),
('Cooking & Baking', 'cooking-baking', 'active', '{}'),
('Travel & Tourism', 'travel-tourism', 'active', '{}'),
('Arts & Crafts', 'arts-crafts', 'active', '{}'),
('Pet Care & Training', 'pet-care-training', 'active', '{}'),
('Gaming', 'gaming', 'active', '{}'),
('Home Improvement', 'home-improvement', 'active', '{}'),
('Beauty & Makeup', 'beauty-makeup', 'active', '{}'),
('Floristry', 'floristry', 'active', '{}'),
('Fitness', 'fitness', 'active', '{}'),
('Yoga', 'yoga', 'active', '{}'),
('Meditation & Mindfulness', 'meditation-mindfulness', 'active', '{}'),
('Nutrition & Diet', 'nutrition-diet', 'active', '{}'),
('Mental Health', 'mental-health', 'active', '{}'),
('Self Defense', 'self-defense', 'active', '{}'),
('Sports', 'sports', 'active', '{}'),
('Leadership', 'leadership', 'active', '{}'),
('Personal Productivity', 'personal-productivity', 'active', '{}'),
('Public Speaking', 'public-speaking', 'active', '{}'),
('Emotional Intelligence', 'emotional-intelligence', 'active', '{}'),
('Time Management', 'time-management', 'active', '{}'),
('Career Development', 'career-development', 'active', '{}'),
('Memory & Study Skills', 'memory-study-skills', 'active', '{}'),
('Financial Literacy', 'financial-literacy', 'active', '{}'),
('Digital Photography', 'digital-photography', 'active', '{}'),
('Photography Fundamentals', 'photography-fundamentals', 'active', '{}'),
('Video Editing', 'video-editing', 'active', '{}'),
('Video Production', 'video-production', 'active', '{}'),
('Commercial Photography', 'commercial-photography', 'active', '{}'),
('Cinematography', 'cinematography', 'active', '{}'),
('Instruments', 'instruments', 'active', '{}'),
('Music Production', 'music-production', 'active', '{}'),
('Music Theory', 'music-theory', 'active', '{}'),
('Singing & Vocals', 'singing-vocals', 'active', '{}'),
('Music Software', 'music-software', 'active', '{}'),
('English Language', 'english-language', 'active', '{}'),
('Foreign Languages', 'foreign-languages', 'active', '{}'),
('Mathematics', 'mathematics', 'active', '{}'),
('Science', 'science', 'active', '{}'),
('Humanities', 'humanities', 'active', '{}'),
('Test Prep', 'test-prep', 'active', '{}'),
('Research Methodology', 'research-methodology', 'active', '{}'),
('Online Education', 'online-education', 'active', '{}'),
('Microsoft Excel', 'microsoft-excel', 'active', '{}'),
('Microsoft Office Suite', 'microsoft-office-suite', 'active', '{}'),
('Google Workspace', 'google-workspace', 'active', '{}'),
('SAP / ERP Systems', 'sap-erp-systems', 'active', '{}'),
('Microeconomics', 'microeconomics', 'active', '{}'),
('Macroeconomics', 'macroeconomics', 'active', '{}'),
('Behavioral Economics', 'behavioral-economics', 'active', '{}'),
('International Trade', 'international-trade', 'active', '{}'),
('Econometrics', 'econometrics', 'active', '{}'),
('Economic History', 'economic-history', 'active', '{}'),
('Development Economics', 'development-economics', 'active', '{}'),
('Circular Economy', 'circular-economy', 'active', '{}'),
('Environmental Economics', 'environmental-economics', 'active', '{}'),
('Political Economy', 'political-economy', 'active', '{}'),
('Bitcoin & Blockchain Fundamentals', 'bitcoin-blockchain-fundamentals', 'active', '{}'),
('Ethereum & Smart Contracts', 'ethereum-smart-contracts', 'active', '{}'),
('Decentralized Finance (DeFi)', 'defi', 'active', '{}'),
('NFTs & Digital Art', 'nfts-digital-art', 'active', '{}'),
('Crypto Trading & Technical Analysis', 'crypto-trading-technical-analysis', 'active', '{}'),
('Web3 Development', 'web3-development', 'active', '{}'),
('Metaverse & Virtual Worlds', 'metaverse-virtual-worlds', 'active', '{}'),
('Tokenomics', 'tokenomics', 'active', '{}'),
('DAO (Decentralized Autonomous Organizations)', 'dao', 'active', '{}'),
('Crypto Security & Wallet Management', 'crypto-security-wallet-management', 'active', '{}'),
('Mining & Staking', 'mining-staking', 'active', '{}'),
('Art History', 'art-history', 'active', '{}'),
('World Religions', 'world-religions', 'active', '{}'),
('Sociology', 'sociology', 'active', '{}'),
('Anthropology', 'anthropology', 'active', '{}'),
('Mythology & Folklore', 'mythology-folklore', 'active', '{}'),
('Cultural Heritage', 'cultural-heritage', 'active', '{}'),
('Cross-Cultural Communication', 'cross-cultural-communication', 'active', '{}'),
('Philosophy', 'philosophy', 'active', '{}'),
('Ethics & Morality', 'ethics-morality', 'active', '{}'),
('Modern History', 'modern-history', 'active', '{}'),
('Asian Studies', 'asian-studies', 'active', '{}'),
('European Literature', 'european-literature', 'active', '{}'),
('Business Law', 'business-law', 'active', '{}'),
('International Law', 'international-law', 'active', '{}'),
('Intellectual Property', 'intellectual-property', 'active', '{}'),
('Political Science', 'political-science', 'active', '{}'),
('Human Rights', 'human-rights', 'active', '{}'),
('General Psychology', 'general-psychology', 'active', '{}'),
('Child Psychology', 'child-psychology', 'active', '{}'),
('Cognitive Psychology', 'cognitive-psychology', 'active', '{}'),
('Social Psychology', 'social-psychology', 'active', '{}'),
('Forensic Psychology', 'forensic-psychology', 'active', '{}'),
('Sustainability & Green Living', 'sustainability-green-living', 'active', '{}'),
('Urban Planning', 'urban-planning', 'active', '{}'),
('Astronomy & Space Science', 'astronomy-space-science', 'active', '{}'),
('Journalism & Media', 'journalism-media', 'active', '{}'),
('Creative Writing', 'creative-writing', 'active', '{}'),
('Public Policy', 'public-policy', 'active', '{}')
ON CONFLICT (slug) DO NOTHING;
