export const UI_LABELS = {
  AUTH: {
    BACK_TO_HOME: "Quay lại Trang chủ",
    WELCOME_BACK: "Chào mừng trở lại!",
    LOGIN_SUBTITLE:
      "Chào mừng bạn quay trở lại với Học Từ Thiện. Vui lòng nhập thông tin để truy cập vào tài khoản của bạn.",
    SIGN_IN_WITH_GOOGLE: "Đăng nhập bằng Google",
    OR_CONTINUE_WITH_EMAIL: "hoặc tiếp tục với email",
    EMAIL_ADDRESS: "Địa chỉ Email",
    PASSWORD: "Mật khẩu",
    FORGOT_PASSWORD: "Quên mật khẩu?",
    ENTER_LOGIN: "Đăng nhập",
    ENTERING: "Đang vào hệ thống...",
    REMEMBER_ME: "Ghi nhớ tôi",
    NEW_TO_ACCOUNT: "Bạn chưa có tài khoản?",
    CREATE_ACCOUNT: "Tạo tài khoản mới",
    POLICY: "Chính sách",
    ABOUT_US: "Về chúng tôi",
    REPORT_ISSUE: "Báo lỗi",
    CREATE_ACCOUNT_TITLE: "Khai phá tiềm năng của bạn",
    CREATE_ACCOUNT_SUBTITLE: "Tạo tài khoản để truy cập vào kho tài nguyên học thuật độc quyền của chúng tôi.",
    FULL_NAME: "Họ và tên",
    CONFIRM_PASSWORD: "Xác nhận mật khẩu",
    SIGN_UP_WITH_GOOGLE: "Google",
    SIGN_IN_WITH_GITHUB: "GitHub",
    OR_QUICK_AUTH: "HOẶC ĐĂNG KÝ NHANH VỚI",
    SIGNING_UP: "Đang tạo tài khoản...",
    ALREADY_HAVE_ACCOUNT: "Bạn đã có tài khoản?",
    AGREE_TO_TERMS: "Tôi đồng ý với",
    TERMS_OF_SERVICE: "Điều khoản dịch vụ",
  },
} as const;
