name: CI and Trigger Deploy
on:
  push:
    branches: [main] # Gấm kiểm tra xem nhánh của mình là 'main' hay 'master' nhé

jobs:
  check-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build check
        run: npm run build # Nếu code lỗi, bước này sẽ đỏ và dừng lại luôn

      - name: Trigger Coolify Deploy
        if: success() # Chỉ khi Build check thành công mới chạy bước này
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK_URL }}'
