# Generated by Django 5.2.8 on 2025-11-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mentors', models.ManyToManyField(blank=True, related_name='skills', to='core.mentorprofile')),
            ],
        ),
    ]
